### ISSUE TITLE
Version 0.22.0 does not work on docker

### ISSUE THREAD

**Issue by elalemanyo** [avencera/rustywind#106]
The latest version gives me this error when I use it inside docker:
```
# npm run rustywind

> rustywind
> rustywind

/usr/src/app/node_modules/.bin/rustywind: 1: empty: not found
```

I have created a small [repo](https://github.com/elalemanyo/rustywind-test) to test it. If I downgrade to version 0.21.0 the error disappears.

**Comment by praveenperera** [comment]
ya thats not gonna work, you got to build with cargo, like the dockerfile in the repo or install it with `npm i -g rustywind`

https://github.com/avencera/rustywind/blob/master/Dockerfile

**Comment by elalemanyo** [comment]
@praveenperera Using `npm i -g rustywind` makes no difference 😔
Build it with cargo doesn't seem normal to me, it's about installing it as a dev dependency of a project running on docker 🤔

**Comment by praveenperera** [comment]
@elalemanyo use the dockefile we have its a multistage build, the final stage doesn't have cargo or anything, its doesn't even have an os because its `FROM scratch`. Its going to be much smaller than a docker image with node and npm in it. 

Build the docker images for yourself and see the sizes.

**Comment by elalemanyo** [comment]
@praveenperera But what I'm trying to do is to install it inside a container running an application I'm working on. For this I use yarn. That worked before the update without problems. I think it is something that should work without major problem, no?

**Comment by therealparmesh** [comment]
Same issue for me. `bunx rustywind` exits with error code in Docker, so it's not working as a `devDependency`.

**Comment by praveenperera** [comment]
```
❯ bunx rustywind --version
RustyWind v0.23.1
```

Works for me i'm not sure why its pulling an old version for you

try 

```
 bunx rustywind@0.23 --version
```

or

```
 bunx rustywind@latest --version
```
