### ISSUE TITLE
Breaking change between v0.1.3 and v0.1.4

### ISSUE THREAD

**Issue by ilyvion** [avencera/rustywind#111]
Adding this field is a breaking change between rustywind_core v0.1.3 and v0.1.4 and shouldn't be a "minor version" bump:
https://github.com/avencera/rustywind/blob/ae6084a00d1c43e924f2692643d27ac457bc7e7c/rustywind-core/src/sorter.rs#L91

**Comment by praveenperera** [comment]
sorry about that, i will yank it
