### ISSUE TITLE
Getting source code from stdin

### ISSUE THREAD

**Issue by shackra** [avencera/rustywind#19]
Hi!

thanks for the tool!

I would like to request a feature, an optional ... option jaja, for receiving source code from stdin, and easy a bit integrating the tool with Emacs via [reformatter.el](https://github.com/purcell/reformatter.el#define-commands-which-run-reformatters-on-the-current-emacs-buffer), right now the reformatting part can run before the file is even written to disk, thus triggering an error in `rustywind`:

```
~ via ⬢ v15.5.0
➜ echo "" | rustywind
RustyWind 0.7.0
Praveen Perera <praveen@avencera.com>

Organize all your tailwind classes

USAGE:
    Run rustywind with a path to get a list of files that will be changed
      rustywind . --dry-run

    If you want to reorganize all classes in place, and change the files run with the `--write` flag
      rustywind --write .

    rustywind [FLAGS] <PATH>

FLAGS:
        --allow-duplicates    When set, rustywind will not delete duplicated classes
        --dry-run             Prints out the new file content with the sorted classes to the terminal
    -h, --help                Prints help information
    -V, --version             Prints version information
        --write               Changes the files in place with the reorganized classes

ARGS:
    <PATH>    A file or directory to run on
~ via ⬢ v15.5.0
✖ echo $?
1
```

For the time being I'm passing the full path of the file, that should work, but in this edge cases where there is no file on disk yet, making `reformatter.el` trigger an error (rightly so).

**Comment by shackra** [comment]
Oops, so, I was working right now, made a change on file, saved and well:

![Captura de Pantalla 2021-01-06 a la(s) 10 57 29](https://user-images.githubusercontent.com/1055216/103797339-fa5b0c80-500d-11eb-8fcd-d0e89d559be7.png)

I can work around this, but outputting that banner to stdout is a no-no

**Comment by shackra** [comment]
on a second thought, using `--write` causes an issue with Emacs where the current contents being written into the file overwrites what `rustywind` just did 🤔.

**Comment by praveenperera** [comment]
Hey @shackra, I made a PR for this feature check it out at:  #21 

Can you test it for me. To test it install the rust compiler here: https://www.rust-lang.org/tools/install

And create a binary with `cargo build --release`

If you're on linux or MacOS you could run the local release script

`./local-release`

That will create a binary and move it to `/usr/local/bin/` so you an run it.

You can run it as:

`echo "hello" | rustywind --stdin`

**Comment by shackra** [comment]
Thanks for the work!

I noticed that nothing is output if you send something with nothing that can be detected to contain Tailwind classes, for instance:

```
rustywind/target/release on  read-from-stdin
➜ echo '<div classNames="px-2 border-0 text-green-200" />' | ./rustywind --stdin
rustywind/target/release on  read-from-stdin
➜ echo $?
0
```

I incorrectly passed a wrong prop `classNames`, and nothing is output and the returned value is 0 instead of something else like 1.

When you do this with prettier you see the following:

```
rustywind/target/release on  read-from-stdin
✖ echo "hello" | prettier --stdin-filepath hello.css
[error] hello.css: SyntaxError: (postcss) CssSyntaxError Unknown word (1:1)
[error] > 1 | hello
[error]     | ^
[error]   2 |
rustywind/target/release on  read-from-stdin
✖ echo $?
2
```

if rustywind won't output something, it better returns something different than 0.

**Comment by praveenperera** [comment]
Thats a good idea, I will implement that. Lets continue any more feedback in the PR.
