### ISSUE TITLE
there is different ordering between rustywind and VSCode's headwind

### ISSUE THREAD

**Issue by shackra** [avencera/rustywind#22]
discussing with a coworker he noted that my commits had a different ordering of classes compared to what headwind does.

For instance, rustywind would order `bg-gray-200`, `pb-12` and `h-full` as `pb-12 h-full bg-gray-200`, however, Headwind will produce `h-full pb-12 bg-gray-200`.

In some other instances the ordering will match, like `whitespace-normal`, `inline-block` and `p-4`  is sorted as `inline-block p-4 whitespace-normal` by both rustywind and headwind.

Why does this happen? I cannot pin-point a pattern of sorting between the two pieces of software. ~This is a weird bug since both rustywind and headwind come from the same author.~

**Comment by praveenperera** [comment]
Hey @shackra this is because the a new version of Headwind needs to be released. If you built the headwind plugin from source and ran it you should see the same order as RustyWind. I'll ask @heybourne if he can release a new version.

**Comment by shackra** [comment]
> I'll ask @heybourne if he can release a new version.

so, did he update the add-on on vscode after all?

**Comment by praveenperera** [comment]
Ya it was released on the 15th
