### ISSUE TITLE
Add custom regexes and multple regex support 

### ISSUE THREAD

**Issue by petertriho** [avencera/rustywind#27]
In a similar fashion to https://github.com/ryanhhhh/headwind/pull/111, I would love to see support for custom regex and support for passing in multi-step regexes.

I don't know rust, and not making any promises but I might look into this if you are open to this?

**Comment by praveenperera** [comment]
Hey @petertriho, I've honestly been meaning to add custom regex support to RustyWind for so long, I just have not had the time. It would be awesome if you could take a look at it. And I'll be available to help you out if you have any questions. Are you on discord?

**Comment by petertriho** [comment]
Awesome! 

Yep I am. My discord is trihonometry#4469

**Comment by praveenperera** [comment]
Great I’ve added you. Message me on there if you have any questions.

**Comment by anukul** [comment]
Seems like a babel plugin would be a much better fit for this sort of thing, since it allows you to operate on the AST instead of fighting 100 variations of strings in code
