### ISSUE TITLE
Only output files that are actually written to

### ISSUE THREAD

**Issue by Jeroen-G** [avencera/rustywind#35]
Would it be easy to have the command with `--write` list only the files that have been changed?

Right now it says "write mode is active the following files are being saved:" with all files even though some (or none) had to be changed.

My reason to have this would be to use it in CI/CD: if the output contains lists a file it means someone has committed non-linted code.

**Comment by praveenperera** [comment]
I'm thinking a different flag like `check-formatted` might be better for this

**Comment by Jeroen-G** [comment]
That would work for me as well! 👍

**Comment by JoeWoodward** [comment]
Also interested in this being a feature. Currently not possible to create CI/CD checks to prevent non-linted code from being shipped without building a manual flow to write, check if any files are unstaged in git, then checkout, and fail.
