### ISSUE TITLE
Two sorting issues - `text` and `border` classes

### ISSUE THREAD

**Issue by rushi** [avencera/rustywind#38]
Hi, I continue to use rustywind. These are some sorting changes I feel are wrong:

**Issue 1:** Border classes are broken up out of order. It is changed so that `border-b border-gray-lighter` are put in different locations 
![CleanShot 2021-08-01 at 20 14 36@2x](https://user-images.githubusercontent.com/65708/127775139-df389d82-44d5-4d0c-b45f-4c19cf22f517.png)

All border related classes should be together.

---

**Issue 2:** `text-*` classes are not grouped together. In this situation `lg:space-x-3` is inserted in between `text-sm` and `text-gray-darker`

![CleanShot 2021-08-01 at 20 21 24@2x](https://user-images.githubusercontent.com/65708/127775331-5ebf7cc8-df96-4dbe-b19a-84fdcf083b01.png)

---

**Comment by rushi** [comment]
This may have todo with the fact that my color scheme is custom, and doesn't use the default numbering scheme of Tailwind like `-500, -600` etc. Is there any way to easily generate a custom `defaults.rs` for my project?

**Comment by praveenperera** [comment]
Hey @rushi yes this is because your custom classes aren't included in sorting. 

I would need to add a flag to allow users to use a custom sorting array. 

I'm thinking a config file where you can add a JSON array.

**Comment by rushi** [comment]
Ok, that sounds great. When it gets implemented, I can help test since I have several large projects to test it on.
