### ISSUE TITLE
Windows 10 bash: line 1: empty: command not found

### ISSUE THREAD

**Issue by thousandsofraccoons** [avencera/rustywind#40]
Hello, thank you for the library. Couldn't start it. 
`C:\Program Files\nodejs/node_modules/rustywind/bin/rustywind: line 1: empty: command not found`
`

**Comment by nelsonmestevao** [comment]
I got today the same problem. Any idea?

**Comment by nelsonmestevao** [comment]
I think it has something to do with `npm config set ignore-scripts true` because the same happens on my Linux machine.

**Comment by praveenperera** [comment]
NPM is blocking if you have the `ignore-scripts` feature turned to true. Thanks @nelsonmestevao 

You can either turn that off or install via our script 

`curl -LSfs https://avencera.github.io/rustywind/install.sh | sh -s -- --git avencera/rustywind`
