### ISSUE TITLE
Problem with ERROR and exit status code 2 if STDIN has no classes

### ISSUE THREAD

**Issue by shackra** [avencera/rustywind#49]
for those like me that use [Apheleia](https://github.com/raxod502/apheleia) for running formatters in chain, this error blocks the chain of formatters from continuing:

> **Warning**: At the moment there's no smart or configurable error handling in place. This means if one of the configured       formatters fail (for example if `isort` isn't installed) then apheleia just doesn't format the buffer at all, even if `black` is installed.

Thus, this:

https://github.com/avencera/rustywind/blob/28a2523ee6eff5db70483bbe3820bf2e88ca4e6c/src/main.rs#L108-L112

Won't cut it. Instead, a warning should be issued and the text from STDIN return as-is.

**Comment by praveenperera** [comment]
Ya I think that's fine. You can do a PR for

```diff
-    eprint!("[ERROR] No classes were found in STDIN"); 
+    eprint!("[WARN] No classes were found in STDIN"); 
-    std::process::exit(2) 
```

**Comment by shackra** [comment]
Pull request created
