### ISSUE TITLE
Downloading rustywind failed: Error: Request failed: 403

### ISSUE THREAD

**Issue by jellydn** [avencera/rustywind#67]
Hi, @artemkovalyov Thank you for your fantastic work. 

I got the below error on my GitHub Action. I'm not sure how to solve this the way it needs to download files based on the os at runtime.

```sh
error /node_modules/rustywind: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /node_modules/rustywind
Output:
Finding release for v0.15.1
GET https://api.github.com/repos/avencera/rustywind/releases/tags/v0.15.1
Deleting invalid download cache
Downloading rustywind failed: Error: Request failed: 403
```

**Comment by jellydn** [comment]
Or we could have opt-out option if that's running on CI/CD. What do you think?

**Comment by jellydn** [comment]
I guess the issue due to rate limit with Github API. If so, what if we could use something library like https://unjs.io/ungh?

```
 UNGH
Unlimited access to GitHub API

Why UNGH?
Accessing to open source GitHub repository meta-data should be fast, easy, and straightforward. GitHub API is rate limited and requires an authentication token to increase limits. Even by using an API token, we need to share or generate it for each deployment and local development of apps and also deal with (increased) rate limits and deployment caching. GitHub REST API is also complex with (unnecessary) bigger payloads because of backward compatibility.

UNGH provides a simplified, cached, and anonymous layer to make GitHub API more enjoyable!
```

**Comment by jellydn** [comment]
One more option is adding env like https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.configuration.skipdownload.md

```
Can be overridden by PUPPETEER_SKIP_DOWNLOAD.
```
For example: RUSTYWIND_SKIP_DOWNLOAD

**Comment by adamdicarlo0** [comment]
> I guess the issue due to rate limit with Github API. If so, what if we could use something library like https://unjs.io/ungh?

I gave this a try, and found a couple of blocking issues:

* https://ungh.cc/repos/avencera/rustywind/releases is broken (HTTP 422).
* In general, the `releases` info on ungh does not include asset links, which is what this installer needs. See https://ungh.cc/repos/avencera/rustywind/releases/latest, for instance. Same thing though the /releases endpoint (when tested on the example given in the README, which does load).

**Comment by jellydn** [comment]
I see. Thanks @adamdicarlo0 Or we could do this option:`RUSTYWIND_SKIP_DOWNLOAD`. What do you think?

**Comment by jellydn** [comment]
FYI - Reported issue to https://github.com/unjs/ungh/issues/30

**Comment by adamdicarlo0** [comment]
To make sure I understand the proposal:

If we skip the download, that means rustywind can't actually be run... but at least the npm install is "successful", enabling CI steps that don't actually need to run rustywind?

**Comment by jellydn** [comment]
> If we skip the download, that means rustywind can't actually be run... but at least the npm install is "successful", enabling CI steps that don't actually need to run rustywind?
Yes, correct. We could print to console that is skip download CLI so if you need to have global rustywind install or binary one. Thanks.

**Comment by adamdicarlo0** [comment]
@jellydn haven't tried it out in our CI yet--probably won't until after holidays--but I just pushed up https://github.com/avencera/rustywind/pull/68 🤞🏻

**Comment by jellydn** [comment]
Could you publish it as the prerelease version? Then I could take a try with my GitHub Action. Thanks.

**Comment by adamdicarlo0** [comment]
@jellydn not sure when the maintainer will get to reviewing my PR, so in the meantime you can do this to install it:

```
cd ~
git clone https://github.com/CareRevolutions/rustywind.git
cd rustywind
git checkout fix-fails-due-to-rate-limiting
cd npm
npm i
npm pack
```

then go to your project and do

```
npm i -D ~/rustywind/rustywind-0.15.1.tgz
```

OR, if you prefer, untarball it into a `vendor` directory in your project, and npm install it from there:

```
mkdir vendor
cd vendor
tar xf ~/rustywind/rustywind-0.15.1.tgz
mv package rustywind
cd ..
npm i -D vendor/rustywind
```

**Comment by jellydn** [comment]
Oh, I see. Thanks for clarify :)

**Comment by jellydn** [comment]
FYI - The PR is working well. I've changed on my `package.json` then I didn't get any 403 error.

```json
 "rustywind": "https://github.com/avencera/rustywind",
```

**Comment by theo-m** [comment]
Thanks for documenting @jellydn! Hoping we can get a release soon tho

**Comment by praveenperera** [comment]
@theo-m released
