### ISSUE TITLE
Cargo.lock not updated in 0.15.3 release

### ISSUE THREAD

**Issue by iamwacko** [avencera/rustywind#70]
If the tarball for the 0.15.3 release is downloaded and `cargo build --locked` is run, then this happens:
```
the lock file Cargo.lock needs to be updated but --locked was passed to prevent this
```
This is because the Cargo.lock still shows rustywind at `0.15.2`, while the Cargo.toml shows it at `0.15.3`.

**Comment by praveenperera** [comment]
Thanks I will fix it @iamwacko

**Comment by praveenperera** [comment]
@iamwacko  Release `0.15.4` https://github.com/avencera/rustywind/releases/tag/v0.15.4
