### ISSUE TITLE
Use same sort order as official Prettier plugin

### ISSUE THREAD

**Issue by Cretezy** [avencera/rustywind#75]
Rustywind doesn't give the same sorting order as https://tailwindcss.com/blog/automatic-class-sorting-with-prettier. This makes it impossible to use both tools in parallel.

They detail how it sorts the classes inside the blog post.

**Comment by tobimori** [comment]
Desperately need this1

**Comment by praveenperera** [comment]
@tobimori @Cretezy this defines the sort order, I'm not sure exactly which order the tw official plugin is in: https://github.com/avencera/rustywind/blob/e3c11f86c99a242d6ac3bf21f7e2fb2c15b1f69d/src/defaults.rs#L9

But PRs are welcome.

If I get some time, I'll try to figure it out. 

Out of curiosity what is the main reason you guys aren't just using the official tool? RustyWind was developed before tailwind released their tool and I'm trying to figure out if it makes sense to keep developing this tool.

**Comment by tobimori** [comment]
> Out of curiosity what is the main reason you guys aren't just using the official tool? RustyWind was developed before tailwind released their tool and I'm trying to figure out if it makes sense to keep developing this tool.

The plugin requires prettier, which doesn't work with some languages that aren't plain HTML/JS/etc.
I have this tool configured with Run on Save to sort my classes in plain PHP templates, and it works great for that! Headwind works partly, but is also outdated and doesn't support newer utilities.

**Comment by praveenperera** [comment]
If you guys can help me figure out which classes need the order changed I can make the changes and release a new version

**Comment by tobimori** [comment]
> If you guys can help me figure out which classes need the order changed I can make the changes and release a new version.
> 
> Probably also need to add some of the newer utilities.

Really depends on how advanced you want this to be. Generally, the official plugin does a lot more than providing a simple list of classes and sorting for that by utilizing the actual Tailwind core compilation process for "getting things sorted". This would also rely on parsing the config so it won't be as simple...

**Comment by praveenperera** [comment]
That has been my idea to implement for a while to sort the config. Does TW prettier use the order in which the classes appear in the output.css file as the sort order?

**Comment by tobimori** [comment]
> That has been my idea to implement for a while to sort the config. Does TW prettier use the order in which the classes appear in the output.css file as the sort order?

Exactly.

**Comment by praveenperera** [comment]
@Cretezy @tobimori implemented in: https://github.com/avencera/rustywind/pull/76

Need to test it

**Comment by bluz71** [comment]
@praveenperera,

> Out of curiosity what is the main reason you guys aren't just using the official tool? RustyWind was developed before tailwind released their tool and I'm trying to figure out **if it makes sense to keep developing this tool**.

Sorry to bump an old issue.

Rustywind is an invaluable tool; Prettier does not work on Ruby on Rails ERB template files whilst Rustywind via the regex option works very well. I have just started using Tailwind on a new Rails project and Rustywind has proven a necessity. It works very well inside Neovim via the Conform plugin.

Please continue working on this tool, it serves a genuine purpose.

Many thanks for this very useful tool.

**Comment by jondkinney** [comment]
@bluz71 your use case is my use case, and I agree, please keep developing the tool, @praveenperera! 

However, I'm not able to get any of the custom regex pattern to work properly. Even the simplest  pattern doesn't seem to match and results an no changes are being made.

For example (just at the command line)

```
npx rustywind --custom-regex "(class)=\"(.*)\"" --write app/views/users/invitations/edit.html.erb
```

Results in no changes made to that file, but if I remove the `--custom-regex` flag, it modifies it just fine.

Would you mind sharing your setup/config?

**Comment by jondkinney** [comment]
Oh my gosh...ok, so I guess it's just outdated documentation and/or LLM hallucinations that bit me. Somewhere along the way I read (or some tool I was using thought) we needed to specify TWO capture groups. But I checked the --help and it states just ONE capture group (just the classes). It's working fine now..... 🤦 

Still @bluz71 if you wouldn't mind sharing your regex for Rails/ERB to confirm we land in the same spot, that'd be awesome. Thanks!

**Comment by bluz71** [comment]
> Still [@bluz71](https://github.com/bluz71) if you wouldn't mind sharing your regex for Rails/ERB to confirm we land in the same spot, that'd be awesome. Thanks!

I switched over to [@4az/prettier-plugin-html-erb](https://www.npmjs.com/package/@4az/prettier-plugin-html-erb) a couple months back, it is a new Prettier plugin for ERB templates. I than attach Tailwind's plugin into my projects Prettier toolchain. The end result is that Tailwind classes are sorted along with the the HTML tags AND embedded Ruby. Works well for my projects.
