### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by azzamsa** [avencera/rustywind#80]
Hi.

Is it possible to publish rustywind not only in `npm` but also in `crates.io`?
For me, it is easier to manage Rust CLI app (install/upgrade/etc)

Thanks for rustywind 🏅

**Comment by praveenperera** [comment]
done: https://crates.io/crates/rustywind

**Comment by azzamsa** [comment]
Thank you so much! 🏅

In the future, ` cargo install-update -a` will include this crate update.
