### ISSUE TITLE
Support cargo-binstall

### ISSUE THREAD

**Issue by azzamsa** [avencera/rustywind#81]
Hi.

Would you like to add `cargo-binstall` support for rustywind?
It will help users with slow machines get the binary directly instead of compiling it locally. Many projects has adopted it.

- https://github.com/atuinsh/atuin/blob/14bef9c4a4047e57851c1dad76ae85c121171d49/atuin/Cargo.toml#L14
- https://github.com/nextest-rs/nextest/blob/52fed18b6a55ed8c5e768309e839310f47f14bd1/cargo-nextest/Cargo.toml#L55C2-L55C27
- https://github.com/zellij-org/zellij/blob/efca21a6ed4ab79396cef3b62a2ba615e9748bfc/Cargo.toml#L73

Here is a complete documentation: https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md

**Comment by praveenperera** [comment]
@azzamsa I'm definitely open to it.  Could you do a PR?
