### ISSUE TITLE
Only touch if necessary

### ISSUE THREAD

**Issue by svoop** [avencera/rustywind#88]
I'm trying to integrate rustywind into the build pipeline of a Bridgetown SSG site. However, Bridgetown uses live reloads, so whenever rustywind touches the source files, it triggers a reload which triggers rustywind, which touches the source files... you get the rap.

Checking with `stat`, rustywind in fact touches all files even if the existing file and the reordered files are identical.

Would it be possible to only write files if they have to be written and to skip them if nothing has changed?

(In case this is less efficient than always writing, maybe add a `--force` argument: `--write` only writes if necessary and `--write --force` always writes.)

**Comment by praveenperera** [comment]
Thanks, this was a huge oversight on my part. Fixing this should speed up RustyWind a lot.

**Comment by svoop** [comment]
Cool, thanks for the PR! I'd be happy to test. For Bridgetown, these tools are installed using `yarn`. Bit out of my turf, though: Is there a way I can tell `yarn` to take a particular branch, in this case `avoid-write`?

**Comment by praveenperera** [comment]
@svoop released in `v0.21.0`

**Comment by svoop** [comment]
@praveenperera Works like a charm! The endless loop is now down to two runs and the rebuild is quite a bit faster. To get it down to just one run, the way rustywind is called has to be changed, but that's another problem on the Bridgetown end. Really cool such a quick fix, Christmas is a bit early this year :wink: Thanks a bunch and happy holidays!
