### ISSUE TITLE
Add Support for Sorting Classes in Phlex Components Ruby Syntax

### ISSUE THREAD

**Issue by modagavr** [avencera/rustywind#92]
Hello,

I'm using rustywind to sort Tailwind CSS classes in my Ruby on Rails project. However, I've noticed that it doesn't seem to support the Phlex components Ruby syntax.

Here's an example of the syntax:

`div class: 'mx-auto max-w-3xl py-16 sm:py-32 lg:py-48 text-center' do`

For more information on the Phlex syntax, please refer to the [Phlex documentation](https://www.phlex.fun).

Thank you for considering this feature request.  ❤️

**Comment by praveenperera** [comment]
Hey you can use the custom regex flag to recognize the classes.

**Comment by modagavr** [comment]
> Hey you can use the custom regex flag to recognize the classes.

Awesome, that works! Thank you 🤝

`rustywind app/views --custom-regex "class:\s'([^']+)'" --write`
