### ISSUE TITLE
Feature Request: Able to work with TS file where have class-variance-authority

### ISSUE THREAD

**Issue by brunowego** [avencera/rustywind#93]
Currently RustyWind works perfect with TSX files, but when we have a file like `typography.ts` with `cva` inside, it doesn't work:

```ts
import { cva } from 'class-variance-authority'

const typographyVariants = cva('', {
  variants: {
    variant: {
      h1: 'text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100',
  },
})

export { typographyVariants }
```

**Comment by praveenperera** [comment]
You'll need to use the `--custom-regex` option, see this issue: https://github.com/avencera/rustywind/issues/92

**Comment by brunowego** [comment]
Works! Thanks @praveenperera.

**Comment by loremipson** [comment]
@brunowego do you mind sharing the regex you used? I can't get this to format anything aside from the base classes. Anything in the nested variants object isn't targeted.
