### ISSUE TITLE
Make rustywind available as library

### ISSUE THREAD

**Issue by bram209** [avencera/rustywind#95]
I maintain a formatter for the rust `leptos` framework and would like to use `rustywind` as a library (mainly this function: https://github.com/avencera/rustywind/blob/fe487da5ceecd5c0d2377796b063d53addf799e4/src/sorter.rs#L34C11-L34C67)

Would you be willing to add a `lib.rs` next to the `main.rs`, so that your binary imports from the library instead? This way I can include tailwind class sorting seamlessly in my project (without having to go through the hassle of spawning a new process that calls the CLI).

**Comment by praveenperera** [comment]
@bram209 this has been a plan of mine, I just have not had the time to do it. But its separated out decently, if you wanted to try and move it to a lib.rs, I will publish it as a library to crates.

**Comment by Rolv-Apneseth** [comment]
Hi, I could take this on if no one else wants to (I would love to have `leptosfmt` sort classes using `rustywind`) . What exactly needs to go into the `lib.rs` and what other changes would be required (documentation or anything else)?

Also, can the `Cli` struct be put in `lib.rs`, and if not, any tips on how to keep all the `cli` functionality in `main.rs`? The `Cli` struct looks quite intertwined with `options.rs`, and then that is required by `sorter.rs`

**Comment by praveenperera** [comment]
@Rolv-Apneseth the process would be to change it to a cargo workspace with two packages, `rustywind` and `rustywind-lib`.

The `rustywind` package would be the CLI and would be small containing the clap dependency and calling functions, in the lib package. If you get it started create a PR and allow me to make changes to it, I'll help out. Thanks.

**Comment by Rolv-Apneseth** [comment]
Cool, thanks, I'll do that

**Comment by Rolv-Apneseth** [comment]
Oh nice. Yeah idm either way, up to @praveenperera but very useful as a reference regardless, thanks.

Both of these tools are great, thank you both.

**Comment by praveenperera** [comment]
Splitting it into 3 crates is a good idea. @Rolv-Apneseth it probably makes sense to continue from @bram209's branch.

**Comment by dbgordon09** [comment]
> Hi, I could take this on if no one else wants to (I would love to have `leptosfmt` sort classes using `rustywind`) . What exactly needs to go into the `lib.rs` and what other changes would be required (documentation or anything else)?
> 
> Also, can the `Cli` struct be put in `lib.rs`, and if not, any tips on how to keep all the `cli` functionality in `main.rs`? The `Cli` struct looks quite intertwined with `options.rs`, and then that is required by `sorter.rs`

This exactly what I was hoping to achieve as well! 🎉Let me know how it goes! I would be happy to help out if need be :)

**Comment by Rolv-Apneseth** [comment]
Sure yeah, if you have any thoughts on that PR that would be appreciated

**Comment by rathod-sahaab** [comment]
Thanks @Rolv-Apneseth would be great to use this with dioxus [dioxus](https://github.com/dioxuslabs/dioxus)

**Comment by Rolv-Apneseth** [comment]
This can be closed I guess? @praveenperera 

Libraries linked [in this comment](https://github.com/avencera/rustywind/pull/100#issuecomment-2052209242) for anyone that wasn't following the PR

**Comment by praveenperera** [comment]
Closed by #100
